name: Build and publish data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Deno version
        id: deno-version
        run: echo "version=$(yq eval -p toml -o json -r '.tools.deno.version' mise.lock)" >> $GITHUB_OUTPUT
      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: ${{ steps.deno-version.outputs.version }}
      - run: deno run -A ./src/build.ts out
      - uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/deploy-pages@v4
        id: deployment
